apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv
spec:
  storageClassName: image-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/kube-images
