apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: todo-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: karppimc/todo-broadcaster:1
          env:
            - name: NATS_URL
              value: nats://my-nats.todo-space.svc.cluster.local:4222
            - name: EXTERNAL_SERVICE_URL
              value: "http://external-service-url.com/api/messages"
