apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: app-space
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: karppimc/logoutput:latest
          ports:
            - containerPort: 3001
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
      volumes:
        - name: config-volume
          configMap:
            name: logoutput-config
            items:
              - key: information.txt
                path: information.txt
