apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv
  labels:
    type: local
spec:
  storageClassName: todo-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/todo-data
