apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: todo-space-staging  # Staging namespace
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: karppimc/todo-app:latest
          ports:
            - containerPort: 3006
          env:
            - name: BASE_URL
              value: "http://todo-backend-svc:3005"
          imagePullPolicy: Always
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/images
            - name: todo-storage
              mountPath: /usr/src/app/data
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3006
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: image-pvc
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-pvc
