apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: app-space
type: Opaque
data:
    # base64 encoded 'admin'
    POSTGRES_USER: dXNlcm5hbWU=
    # base64 encoded 'adminpassword'
    POSTGRES_PASSWORD: cGFzc3dvcmQ=
    # base64 encoded 'pingpong'
    POSTGRES_DB: cGluZ3Bvbmc=
