apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-deployment
  namespace: app-space
  labels:
    app: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: logoutput
          image: karppimc/logoutput:latest
          ports:
            - containerPort: 3001


