apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: app-space
spec:
  clusterIP: None  # Required for headless service
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
