apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: todo-space
spec:
  schedule: "0 0 * * *" # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: karppimc/cron-hourly-and-backup:latest
            imagePullPolicy: Always  # Ensure latest image is used
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_PASSWORD
            volumeMounts:
            - name: gcs-key
              mountPath: /etc/gcs-key
              readOnly: true
            command:
            - /bin/bash
            - -c
            - |
              pg_dump -h todo-db-svc.todo-space.svc.cluster.local -U username todos > /tmp/todos_backup.sql
              /usr/bin/gsutil -o "Credentials:gs_service_key_file=/etc/gcs-key/key.json" cp /tmp/todos_backup.sql gs://dwk-bucket123/
          restartPolicy: OnFailure
          volumes:
          - name: gcs-key
            secret:
              secretName: gcs-backup-key
