apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
metadata:
  annotations:
    force-redeploy: "true"  # This change will trigger a re-sync without changing the image version
