apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: app-space
spec:
  selector:
    app: pingpong
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
