apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: PROJECT/IMAGE
    newName: karppimc/todo-backend
    newTag: latest
