apiVersion: v1
kind: Secret
metadata:
    name: todo-db-secret
    namespace: todo-space
type: Opaque
data:
    # base64 encoded 'username'
    POSTGRES_USER: dXNlcm5hbWU=
    # base64 encoded 'password'
    POSTGRES_PASSWORD: cGFzc3dvcmQ=
    # base64 encoded 'todos'
    POSTGRES_DB: dG9kb3M=
