apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-app-rollout
  namespace: todo-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: karppimc/todo-app:latest
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: "3006"
        - name: BASE_URL
          value: http://34.88.124.122/api
        volumeMounts:
        - name: image-storage
          mountPath: /usr/src/app/images
        - name: todo-storage
          mountPath: /usr/src/app/data
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3006
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3006
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-pvc
      - name: todo-storage
        persistentVolumeClaim:
          claimName: todo-pvc
