apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: karppimc/todo:1
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
