apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
        - name: todo-server
          image: karppimc/todo-server:1.0
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
