apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-space
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3006
