apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc
  namespace: todo-space
spec:
  selector:
    app: todo-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
