apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
  namespace: todo-space
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
