apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: app-space
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: karppimc/logoutput:latest
          ports:
            - containerPort: 3001
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: MESSAGE
            - name: PINGPONG_HOST
              value: pingpong-svc
            - name: PINGPONG_PORT
              value: "3002"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -s -o /dev/null -w '%{http_code}' http://$PINGPONG_HOST:$PINGPONG_PORT/healthz | grep 200"
            initialDelaySeconds: 10
            timeoutSeconds: 5   
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -s -o /dev/null -w '%{http_code}' http://localhost:3001/ | grep 200"
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config-volume
          configMap:
            name: logoutput-config
            items:
              - key: information.txt
                path: information.txt
