name: Cleanup Environment

on:
  delete:
    branches:
      - '*'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.event.ref }}

jobs:
  cleanup-environment:
    name: Cleanup Kubernetes Namespace
    runs-on: ubuntu-latest

    steps:
      ## ✅ Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      ## ✅ Delete Namespace
      - name: Delete Kubernetes Namespace
        run: |
          if [ "${BRANCH}" != "main" ]; then
            echo "Deleting namespace for branch: ${BRANCH}"
            kubectl delete namespace ${BRANCH} || echo "Namespace not found or already deleted"
          else
            echo "Skipping namespace deletion for main branch"
          fi
