apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - image-pvc.yaml
  - todo-pvc.yaml

images:
  - name: PROJECT/IMAGE
    newName: karppimc/todo
    newTag: latest
